const sources={tse2026:{label:'Eleições 2026 — TSE',url:'https://www.tse.jus.br/eleicoes/eleicoes-2026'},propaganda:{label:'Resolução sobre propaganda — TSE',url:'https://www.tse.jus.br/eleicoes/eleicoes-2026-content/normas-e-documentacoes/arquivos-2026/resolucao-e-voto-propaganda/@@display-file/file/Resolucao-e-voto-propaganda.pdf'},lgpd:{label:'Lei nº 13.709/2018 (LGPD) — Planalto',url:'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm'},eleicoes:{label:'Lei nº 9.504/1997 — Planalto',url:'https://www.planalto.gov.br/ccivil_03/leis/l9504.htm'},anpd:{label:'Guia de segurança da informação — ANPD',url:'https://www.gov.br/anpd/pt-br/documentos-e-publicacoes/guia_seguranca_da_informacao_para_atpps___defeso_eleitoral.pdf'},resultados:{label:'Resultados eleitorais — TSE',url:'https://resultados.tse.jus.br/'},ibge:{label:'Cidades e Estados — IBGE',url:'https://www.ibge.gov.br/cidades-e-estados'},gerber:{label:'Field Experiments and the Study of Voter Turnout — APSR',url:'https://doi.org/10.1017/S0003055400227882'},kreiss:{label:'Prototype Politics — Oxford University Press',url:'https://global.oup.com/academic/product/prototype-politics-9780199350254'},ico:{label:'Caso Cambridge Analytica — ICO do Reino Unido',url:'https://ico.org.uk/action-weve-taken/investigation-into-data-analytics-for-political-purposes/'}};
const phases=[
{days:'Dias 1–5',title:'Governança e conformidade',objective:'Definir quem decide, quem executa e quais controles protegem a campanha desde o primeiro dia.',tasks:['Nomear coordenação geral, jurídico-eleitoral, financeiro e responsável por dados.','Criar matriz de responsabilidades com titular e substituto.','Abrir inventário de dados, riscos e fornecedores.','Validar calendário eleitoral de 2026 e rotina semanal de aprovação.'],questions:['Quem aprova gastos, peças e uso de dados?','Qual é o canal oficial para incidentes e urgências?','Quais bases de dados já existem, de onde vieram e para qual finalidade?'],ideal:'Uma página com organograma, responsáveis, prazos de resposta e registro de decisões; nenhum dado entra sem origem e finalidade.',cases:[['Sucesso · Obama 2008','A integração entre campo, tecnologia e gestão é estudada como exemplo de infraestrutura organizacional. A lição transferível é coordenação — não copiar técnicas de perfilamento.'],['Sucesso · campanhas com experimentos de campo','Estudos de Gerber e Green mostram que rotinas mensuráveis de mobilização podem ser avaliadas com método e transparência.'],['Insucesso · Cambridge Analytica','Uso de dados em contexto político gerou investigação e sanções. Falharam transparência, finalidade e controle sobre dados pessoais.']],refs:['tse2026','lgpd','ico'],explain:'Governança (regras de decisão) e accountability (responsabilização) evitam tarefas sem dono e permitem provar por que um dado foi usado.',law:'LGPD, arts. 6º, 37 e 46: aplique finalidade, registro das operações e segurança desde a concepção.'},
{days:'Dias 6–11',title:'Diagnóstico e território',objective:'Construir uma fotografia verificável do território usando somente dados públicos e agregados.',tasks:['Definir municípios e regiões prioritárias com critério explícito.','Baixar eleitorado e resultados apenas de fontes oficiais.','Registrar data, fonte e nível de confiança de cada número.','Separar população, eleitorado, votos válidos e comparecimento.'],questions:['Quais municípios formam a área de atuação real?','Qual dado está confirmado, estimado ou ainda não encontrado?','Onde a equipe já possui presença física verificável?'],ideal:'Mapa operacional por município com fonte, data de referência, presença da equipe e lacunas; nenhuma inferência sobre indivíduo.',cases:[['Sucesso · mapas de cobertura','Campanhas territoriais usam unidades geográficas para organizar agenda e equipe; o ganho vem da logística clara.'],['Sucesso · resultados oficiais abertos','O TSE permite comparar votação passada por território sem criar perfis pessoais.'],['Insucesso · população tratada como eleitorado','Misturar população do IBGE com cadastro eleitoral produz metas, orçamento e cobertura errados.']],refs:['resultados','ibge','tse2026'],explain:'Dado agregado (total de um grupo) reduz o risco de identificar pessoas. Correlação (duas medidas que variam juntas) não prova causa nem intenção de voto.',law:'LGPD, art. 6º, III, e Resolução TSE nº 23.610/2019: use o mínimo necessário e respeite a finalidade original.'},
{days:'Dias 12–17',title:'Estratégia e metas',objective:'Transformar a meta de 60 mil votos em hipóteses operacionais revisáveis, sem apresentá-la como previsão.',tasks:['Registrar a meta como cenário administrativo, não promessa.','Distribuir metas de presença, conversas e voluntariado por semana.','Criar cenários conservador, base e expansão.','Definir critérios objetivos para revisar o plano.'],questions:['Que capacidade semanal a equipe realmente possui?','Quais premissas sustentam cada cenário?','Qual sinal fará aumentar, manter ou reduzir uma ação?'],ideal:'Planilha de cenários com premissas, capacidade e margem de incerteza; voto projetado nunca aparece como fato.',cases:[['Sucesso · gestão por cenários','Equipes resilientes trabalham com faixas e gatilhos, reduzindo decisões baseadas em entusiasmo.'],['Sucesso · metas de processo','Acompanhar portas, reuniões e cobertura permite corrigir execução antes do resultado final.'],['Insucesso · precisão falsa','Projetar votos exatos com amostra fraca cria segurança indevida e desvia recursos.']],refs:['resultados','gerber','kreiss'],explain:'Indicador antecedente (medida que muda antes do resultado) ajuda a gerir esforço. Cenário (hipótese condicionada) não é previsão.',law:'Lei nº 9.504/1997 e normas de pesquisa eleitoral: não publique simulações internas como pesquisa sem cumprir as exigências aplicáveis.'},
{days:'Dias 18–24',title:'Mensagem e propostas',objective:'Organizar propostas verificáveis e linguagem consistente, sem desinformação ou manipulação.',tasks:['Definir três prioridades estaduais compatíveis com o cargo.','Criar ficha de evidências para cada afirmação.','Aprovar guia de tom, resposta e correção de erro.','Registrar uso de IA e revisão humana em toda peça sintética.'],questions:['Qual problema estadual cada proposta resolve?','Que evidência pública sustenta a afirmação?','O que a candidatura não pode prometer por falta de competência legal?'],ideal:'Uma ficha por proposta com problema, competência estadual, evidência, custo ou limite conhecido e versão em linguagem simples.',cases:[['Sucesso · mensagem disciplinada','Campanhas reconhecíveis repetem prioridades verificáveis e adaptam formato, não os fatos.'],['Sucesso · checagem prévia','Biblioteca de afirmações aprovadas reduz contradições e acelera resposta.'],['Insucesso · conteúdo manipulado','Peças falsas ou descontextualizadas criam risco jurídico, reputacional e de retirada.']],refs:['propaganda','tse2026','eleicoes'],explain:'Framing (enquadramento) organiza uma questão; não autoriza omitir fato essencial. Conteúdo sintético (gerado ou alterado por IA) exige transparência conforme a regra vigente.',law:'Resolução TSE nº 23.610/2019, com alterações de 2026, disciplina conteúdo fabricado/manipulado, IA e propaganda na internet.'},
{days:'Dias 25–32',title:'Campo e mobilização',objective:'Executar presença territorial mensurável com abordagem respeitosa e adesão voluntária.',tasks:['Montar agenda territorial com responsáveis e capacidade.','Treinar equipe sobre abordagem, consentimento e descadastro.','Criar ficha de evento apenas com totais agregados.','Realizar lote-piloto antes de ampliar a operação.'],questions:['Quantas pessoas e horas estão disponíveis por território?','Como será registrado um pedido para não receber contato?','Qual foi o resultado do piloto e o que deve mudar?'],ideal:'Agenda semanal, roteiro de abordagem, checklist do evento e registro de totais; contatos individuais só entram com informação e base legal.',cases:[['Sucesso · contato pessoal testado','Experimentos de campo encontraram efeitos diferentes por método; medir o processo é melhor que presumir impacto.'],['Sucesso · piloto pequeno','Testes limitados revelam falhas de roteiro e capacidade antes de escalar.'],['Insucesso · lista sem origem','Bases compradas ou reaproveitadas sem finalidade compatível expõem a campanha a descadastro, denúncia e sanção.']],refs:['gerber','lgpd','propaganda'],explain:'Piloto (teste controlado em pequena escala) reduz risco. Taxa de conversão operacional (adesões consentidas divididas por conversas) mede o fluxo, não intenção de voto.',law:'LGPD, arts. 7º, 8º e 18: documente a base legal, torne o consentimento demonstrável quando usado e facilite revogação e direitos.'},
{days:'Dias 33–40',title:'Conteúdo e distribuição',objective:'Manter uma cadência de conteúdo legal, acessível e mensurável em canais oficiais.',tasks:['Criar calendário editorial por tema, formato e responsável.','Aplicar checklist jurídico e factual antes de publicar.','Registrar impulsionamento, contratação e biblioteca de peças.','Garantir legendas, contraste e texto alternativo.'],questions:['Qual é o objetivo operacional de cada peça?','Quem verificou fatos, direitos autorais e regra eleitoral?','A peça é compreensível sem áudio e por leitores de tela?'],ideal:'Calendário enxuto com uma ação principal por peça, aprovação registrada e versões acessíveis.',cases:[['Sucesso · operação multicanal integrada','A literatura sobre campanhas digitais destaca integração entre equipe e canais, não volume isolado.'],['Sucesso · biblioteca de peças','Versionamento e aprovação reduzem erro e permitem auditoria.'],['Insucesso · impulsionamento informal','Contratação fora das formas permitidas ou sem identificação pode gerar retirada e responsabilização.']],refs:['propaganda','kreiss','tse2026'],explain:'Cadência (ritmo planejado) e atribuição (relação documentada entre ação e resposta) ajudam gestão, mas métricas de plataforma não equivalem a votos.',law:'Lei nº 9.504/1997, arts. 57-B e 57-C, e Resolução TSE nº 23.610/2019: confira responsáveis, identificação e contratação do impulsionamento.'},
{days:'Dias 41–48',title:'Monitoramento e correção',objective:'Comparar execução com o plano e corrigir gargalos com evidência, sem vigiar indivíduos.',tasks:['Atualizar painel agregado ao fim de cada dia.','Realizar reunião curta de revisão a cada 48 horas.','Registrar decisão, motivo e prazo de reavaliação.','Auditar acessos e pedidos de titulares.'],questions:['Qual gargalo concreto apareceu nos últimos dois dias?','Que mudança pequena será testada agora?','Existe dado sem fonte, finalidade ou prazo de retenção?'],ideal:'Painel com alcance, conversas, adesões consentidas e cobertura; ata curta explica toda mudança relevante.',cases:[['Sucesso · ciclo medir-aprender','Equipes que registram hipótese e resultado conseguem distinguir mudança útil de improviso.'],['Sucesso · indicadores de capacidade','Filas, atrasos e cobertura orientam reforço operacional sem conhecer perfil pessoal.'],['Insucesso · métrica de vaidade','Curtidas e visualizações isoladas podem crescer sem melhorar organização ou presença.']],refs:['anpd','lgpd','resultados'],explain:'Métrica de vaidade (número chamativo sem vínculo claro com objetivo) não deve comandar recursos. Auditoria (verificação documentada) mantém rastreabilidade.',law:'LGPD, arts. 18, 37 e 46: mantenha registro, atenda direitos e proteja os dados durante todo o ciclo.'},
{days:'Dias 49–55',title:'Reta final e encerramento',objective:'Concluir mobilização, votação e transição documental com controle jurídico e financeiro.',tasks:['Validar plano do dia da eleição com jurídico.','Congelar versões finais e contatos de emergência.','Conferir proibições, fiscais, logística e contingências.','Encerrar acessos, exportar registros e executar retenção ou descarte.'],questions:['Quem decide diante de incidente no dia da eleição?','Qual é a versão final aprovada de cada material?','Que dados devem ser eliminados, preservados ou entregues e por qual fundamento?'],ideal:'Sala de situação com contatos, checklists e versão única; depois, termo de encerramento com acessos revogados e dados destinados.',cases:[['Sucesso · comando e contingência','Papéis e versões claras reduzem ruído quando o tempo de resposta é curto.'],['Sucesso · fechamento documentado','Inventário final facilita prestação de contas e resposta a titulares.'],['Insucesso · acesso aberto após a campanha','Contas e planilhas esquecidas ampliam risco de incidente e uso incompatível.']],refs:['tse2026','eleicoes','lgpd'],explain:'Runbook (roteiro operacional para situação crítica) define quem faz o quê. Retenção (manutenção por prazo justificado) não significa guardar tudo indefinidamente.',law:'Lei nº 9.504/1997, LGPD e resoluções TSE de 2026: o jurídico deve validar condutas do dia da eleição, prestação de contas e destino dos dados.'}
];

const expandedTasks={
  0:['Aprovar orçamento inicial e limite de decisão de cada responsável.','Cadastrar fornecedores somente depois da conferência jurídica e financeira.','Criar plano simples para incidente com dados, conta digital ou material irregular.'],
  1:['Listar problemas públicos com fonte e ano, sem completar lacunas por opinião.','Mapear equipamentos, entidades e lideranças usando somente informações públicas.','Criar ficha dos concorrentes baseada em fatos públicos, sem ataque pessoal.'],
  2:['Separar orçamento planejado, contratado e pago.','Definir metas semanais de alcance, eventos, conversas e voluntários.','Marcar toda projeção como cenário (hipótese), nunca como resultado garantido.'],
  3:['Confirmar biografia, partido, número, slogan e identidade visual.','Montar narrativa central (história curta que liga trajetória, problema e proposta).','Preparar respostas simples para entrevistas e perguntas difíceis.'],
  4:['Criar cadastro e treinamento de voluntários com consentimento.','Montar calendário de eventos com local, responsável, capacidade e risco.','Definir roteiro de visita, escuta e retorno para cada cidade.'],
  5:['Montar lista de imprensa e canais regionais usando contatos profissionais públicos.','Criar plano de crise (quem verifica, decide, responde e registra).','Revisar toda mídia feita ou alterada por inteligência artificial antes de publicar.'],
  6:['Comparar orçamento planejado com o gasto realizado.','Medir cada evento por presença, alcance, conversas e custo, sem contar votos.','Registrar correções decididas na reunião de feedback e nas revisões seguintes.'],
  7:['Confirmar fiscais, locais, contatos e plano de emergência do dia da eleição.','Fechar documentos para prestação de contas com a equipe financeira e jurídica.','Revogar acessos de quem não precisa mais entrar no sistema.']
};
const expandedQuestions={
  0:['Quanto pode ser gasto e quem autoriza cada faixa de valor?','Quem deve ser avisado primeiro quando houver um problema?'],
  1:['Quais problemas têm fonte oficial e quais ainda precisam ser confirmados?','Quais informações públicas ajudam a planejar presença sem criar perfil de pessoas?'],
  2:['Qual é o orçamento mínimo, base e máximo?','Que número mostra execução e qual é apenas estimativa?'],
  3:['Qual frase simples explica quem é Kiel, o que defende e por que é candidato?','Que promessa precisa ser retirada por não ser competência de deputado estadual?'],
  4:['Quantos voluntários foram treinados e quem coordena cada cidade?','Como a equipe contará presença sem duplicar pessoas?'],
  5:['Quem pode falar oficialmente em nome da campanha?','Qual é o prazo máximo para confirmar um fato antes de responder?'],
  6:['Qual ação trouxe cobertura com custo e esforço aceitáveis?','Que decisão foi mantida, corrigida ou interrompida e por quê?'],
  7:['Quem comanda cada turno no dia da votação?','Quais contas, arquivos e acessos precisam ser encerrados depois da eleição?']
};
Object.entries(expandedTasks).forEach(([i,items])=>phases[Number(i)].tasks.push(...items));
Object.entries(expandedQuestions).forEach(([i,items])=>phases[Number(i)].questions.push(...items));

const territoryData=[
  {city:'Indaiatuba',census:255748,estimate:269657,density:'820,90',school:'98,62%',pib:'R$ 110.518,41',url:'https://www.ibge.gov.br/cidades-e-estados/sp/indaiatuba.html'},
  {city:'Itu',census:168240,estimate:175047,density:'262,58',school:'96,30%',pib:'R$ 83.288,93',url:'https://www.ibge.gov.br/cidades-e-estados/sp/itu.html'},
  {city:'Salto',census:134319,estimate:141111,density:'1.009,48',school:'97,86%',pib:'R$ 85.609,32',url:'https://www.ibge.gov.br/cidades-e-estados/sp/salto.html'},
  {city:'Porto Feliz',census:56497,estimate:58605,density:'101,48',school:'99,19%',pib:'R$ 89.687,04',url:'https://www.ibge.gov.br/cidades-e-estados/sp/porto-feliz.html'},
  {city:'Cabreúva',census:47011,estimate:48654,density:'180,65',school:'99,97%',pib:'R$ 154.027,39',url:'https://www.ibge.gov.br/cidades-e-estados/sp/cabreuva.html'}
];
const prepLabels=['Terça · 11/08','Terça · 11/08','Terça · 11/08','Quarta · 12/08','Quarta · 12/08','Quarta · 12/08','Quinta · 13/08','Quinta · 13/08'];
const defaultUsers=Array.from({length:10},(_,i)=>`Operador ${String(i+1).padStart(2,'0')}`);
const DB_NAME='centralCampanhaKiel',STORE='state';
let state={tasks:{},answers:{},metrics:[],audit:[],users:[...defaultUsers],currentUser:0,settings:{candidateName:'Kiel Damasceno',slogan:'',primaryColor:'#1800ac',accentColor:'#00d100'}};let activePhase=0;
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function load(){const db=await openDB();const saved=await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get('app');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(saved)state={...state,...saved,users:Array.isArray(saved.users)&&saved.users.length===10?saved.users:[...defaultUsers],audit:Array.isArray(saved.audit)?saved.audit:[],settings:{...state.settings,...saved.settings}};if(state.settings.primaryColor==='#16304a'){state.settings.primaryColor='#1800ac';state.settings.accentColor='#00d100'}applySettings();renderAll()}
async function save(message){const db=await openDB();await new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(state,'app');r.onsuccess=res;r.onerror=()=>rej(r.error)});if(message)toast(message)}
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const actor=()=>state.users[state.currentUser]||defaultUsers[0];
function log(action,detail){state.audit.unshift({at:new Date().toISOString(),actor:actor(),action,detail});state.audit=state.audit.slice(0,2000)}
function renderNav(){document.querySelector('#phase-nav-list').innerHTML=phases.map((p,i)=>`<button type="button" class="${i===activePhase?'active':''}" data-phase="${i}" aria-pressed="${i===activePhase}"><span>${i+1}</span><span>${esc(p.title)}<small>${prepLabels[i]}</small></span><span>${phasePercent(i)}%</span></button>`).join('')}
function phasePercent(i){const done=phases[i].tasks.filter((_,j)=>state.tasks[`${i}-${j}`]).length;return Math.round(done/phases[i].tasks.length*100)}
function renderPhase(){const p=phases[activePhase];document.querySelector('#phase-detail').innerHTML=`<article class="phase-header"><div class="phase-meta"><span class="badge">Módulo ${activePhase+1} de ${phases.length}</span><span class="badge">Preencher: ${prepLabels[activePhase]}</span><span class="badge">${phasePercent(activePhase)}% concluído</span></div><h2>${esc(p.title)}</h2><p class="objective"><strong>Objetivo:</strong> ${esc(p.objective)}</p><p class="chart-help">A linguagem é simples. Quando aparecer um termo do meio político ou técnico, a explicação vem entre parênteses.</p></article><section class="card phase-section"><h3>Tarefas para concluir este módulo</h3><div class="task-list">${p.tasks.map((t,j)=>`<label class="task-item"><input type="checkbox" data-task="${activePhase}-${j}" ${state.tasks[`${activePhase}-${j}`]?'checked':''}><span>${esc(t)}</span></label>`).join('')}</div></section><section class="card phase-section"><h3>Perguntas prontas</h3><div class="question-list">${p.questions.map((q,j)=>`<div class="question-item"><label for="q-${activePhase}-${j}">${esc(q)}</label><textarea id="q-${activePhase}-${j}" data-answer="${activePhase}-${j}" placeholder="Escreva a resposta da equipe de forma simples...">${esc(state.answers[`${activePhase}-${j}`])}</textarea></div>`).join('')}</div></section><section class="card phase-section"><h3>Como o resultado ideal deve ficar</h3><p>${esc(p.ideal)}</p></section><section class="card phase-section"><h3>Exemplos reais (cases) e lições</h3><div class="case-grid">${p.cases.map((c,j)=>`<article class="case ${j===2?'failure':''}"><h4>${esc(c[0])}</h4><p>${esc(c[1])}</p></article>`).join('')}</div></section><section class="card phase-section"><h3>3 fontes para conferir</h3><ol class="source-list">${p.refs.map(k=>`<li><a href="${sources[k].url}" target="_blank" rel="noopener noreferrer">${sources[k].label}</a></li>`).join('')}</ol></section><section class="card phase-section explanation"><h3>Explicação simples</h3><p>${esc(p.explain)}</p><p><strong>Regra aplicada à campanha:</strong> ${esc(p.law)}</p></section><section class="card phase-section"><h3>Salvar e usar fora do site</h3><p>Salve as respostas ou baixe o roteiro pronto para reunião e trabalho externo.</p><div class="phase-actions"><button class="primary" type="button" id="save-phase">Salvar este módulo</button><button class="secondary" type="button" id="download-phase">Baixar roteiro (.md)</button></div></section>`}
function updateProgress(){const total=phases.reduce((n,p)=>n+p.tasks.length,0),done=Object.values(state.tasks).filter(Boolean).length,pct=Math.round(done/total*100);document.querySelector('#progress-value').textContent=`${pct}%`;document.querySelector('#progress-label').textContent=`${done} de ${total} tarefas concluídas`;document.querySelector('#progress-bar').style.width=`${pct}%`}
function groupMetrics(key){return state.metrics.reduce((a,m)=>{const k=m[key]||'Não identificado';a[k]=(a[k]||0)+Number(m.reach||0);return a},{})}
function bars(grouped){const max=Math.max(1,...Object.values(grouped));return Object.keys(grouped).length?Object.entries(grouped).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><strong>${v.toLocaleString('pt-BR')}</strong></div>`).join(''):'<p class="chart-help">O gráfico aparecerá depois do primeiro registro.</p>'}
function renderMetrics(){const totals=state.metrics.reduce((a,m)=>({reach:a.reach+Number(m.reach||0),conversations:a.conversations+Number(m.conversations||0),supporters:a.supporters+Number(m.supporters||0)}),{reach:0,conversations:0,supporters:0});document.querySelector('#kpi-reach').textContent=totals.reach.toLocaleString('pt-BR');document.querySelector('#kpi-conversations').textContent=totals.conversations.toLocaleString('pt-BR');document.querySelector('#kpi-supporters').textContent=totals.supporters.toLocaleString('pt-BR');document.querySelector('#kpi-rate').textContent=totals.conversations?`${(totals.supporters/totals.conversations*100).toFixed(1).replace('.',',')}%`:'0%';document.querySelector('#metric-table').innerHTML=state.metrics.length?state.metrics.map((m,i)=>`<tr><td>${new Date(m.date+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>${esc(m.city||'Não identificado')}</td><td>${esc(m.territory)}</td><td>${esc(m.channel||'Outro')}</td><td>${esc(m.approach||'Outro')}</td><td>${Number(m.reach||0).toLocaleString('pt-BR')}</td><td>${esc(m.actor||'Sistema')}</td><td><button class="text-button danger" data-delete-metric="${i}" type="button">Excluir</button></td></tr>`).join(''):'<tr><td colspan="8">Nenhum alcance registrado.</td></tr>';document.querySelector('#bar-chart').innerHTML=bars(groupMetrics('city'));document.querySelector('#channel-chart').innerHTML=bars(groupMetrics('channel'));document.querySelector('#approach-chart').innerHTML=bars(groupMetrics('approach'));const matrix={};state.metrics.forEach(m=>{const k=`${m.city||'Não identificado'}|||${m.approach||'Outro'}`;matrix[k]=(matrix[k]||0)+Number(m.reach||0)});document.querySelector('#city-approach-table').innerHTML=Object.keys(matrix).length?Object.entries(matrix).sort((a,b)=>b[1]-a[1]).map(([k,v])=>{const [city,approach]=k.split('|||');return `<tr><td>${esc(city)}</td><td>${esc(approach)}</td><td>${v.toLocaleString('pt-BR')}</td></tr>`}).join(''):'<tr><td colspan="3">Nenhum dado para comparar.</td></tr>'}
function renderTerritory(){document.querySelector('#territory-table').innerHTML=territoryData.map(d=>`<tr><td><strong>${d.city}</strong></td><td>${d.census.toLocaleString('pt-BR')}</td><td>${d.estimate.toLocaleString('pt-BR')}</td><td>${d.density} hab./km²</td><td>${d.school}</td><td>${d.pib}</td><td><a href="${d.url}" target="_blank" rel="noopener noreferrer">IBGE</a></td></tr>`).join('')}
function renderUsers(){const select=document.querySelector('#current-user');select.innerHTML=state.users.map((u,i)=>`<option value="${i}" ${i===state.currentUser?'selected':''}>${esc(u)}</option>`).join('');document.querySelector('#user-list').innerHTML=state.users.map((u,i)=>`<span>${i+1}. ${esc(u)}</span>`).join('');document.querySelector('#user-fields').innerHTML=state.users.map((u,i)=>`<label>Operador ${String(i+1).padStart(2,'0')}<input name="user-${i}" value="${esc(u)}" maxlength="40" required></label>`).join('')}
function renderAudit(){document.querySelector('#audit-table').innerHTML=state.audit.length?state.audit.map(a=>`<tr><td>${new Date(a.at).toLocaleString('pt-BR')}</td><td>${esc(a.actor)}</td><td>${esc(a.action)}</td><td>${esc(a.detail)}</td></tr>`).join(''):'<tr><td colspan="4">Nenhuma atividade registrada.</td></tr>'}
function renderAll(){renderNav();renderPhase();updateProgress();renderMetrics();renderTerritory();renderUsers();renderAudit()}
function applySettings(){document.documentElement.style.setProperty('--primary',state.settings.primaryColor||'#1800ac');document.documentElement.style.setProperty('--accent',state.settings.accentColor||'#00d100');document.querySelector('#brand-name').textContent=state.settings.candidateName;const f=document.querySelector('#settings-form');Object.entries(state.settings).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v})}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csv(rows){return '\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n')}
function phaseMarkdown(){const p=phases[activePhase];return `# Módulo ${activePhase+1} — ${p.title}\n\n**Preencher em:** ${prepLabels[activePhase]}\n\n**Objetivo:** ${p.objective}\n\n## Tarefas\n${p.tasks.map((t,j)=>`- [${state.tasks[`${activePhase}-${j}`]?'x':' '}] ${t}`).join('\n')}\n\n## Perguntas e respostas\n${p.questions.map((q,j)=>`### ${q}\n${state.answers[`${activePhase}-${j}`]||'Resposta pendente.'}`).join('\n\n')}\n\n## Resultado ideal\n${p.ideal}\n\n## Explicação simples\n${p.explain}\n\n## Regra aplicada\n${p.law}\n\n## Fontes\n${p.refs.map(k=>`- ${sources[k].label}: ${sources[k].url}`).join('\n')}\n`}
document.addEventListener('click',e=>{const phase=e.target.closest('[data-phase]');if(phase){activePhase=Number(phase.dataset.phase);renderNav();renderPhase();window.scrollTo({top:document.querySelector('.journey-layout').offsetTop-80,behavior:'smooth'})}const nav=e.target.closest('[data-view]');if(nav){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==nav.dataset.view);document.querySelectorAll('[data-view]').forEach(a=>a.classList.toggle('active',a===nav));document.querySelector('#main-nav').classList.remove('open');document.querySelector('.menu-button').setAttribute('aria-expanded','false')}if(e.target.id==='save-phase'){log('Salvou módulo',phases[activePhase].title);save('Módulo salvo no navegador.');renderAudit()}if(e.target.id==='download-phase')download(`modulo-${activePhase+1}.md`,phaseMarkdown(),'text/markdown');if(e.target.matches('[data-delete-metric]')){const m=state.metrics[Number(e.target.dataset.deleteMetric)];log('Excluiu alcance',`${m.territory} · ${Number(m.reach||0).toLocaleString('pt-BR')} pessoas`);state.metrics.splice(Number(e.target.dataset.deleteMetric),1);save('Registro excluído.');renderMetrics();renderAudit()}if(e.target.id==='export-json')download('campanha-kiel-backup.json',JSON.stringify(state,null,2),'application/json');if(e.target.id==='export-csv')download('alcance-campanha.csv',csv([['Data','Cidade','Ação','Canal','Abordagem','Alcance','Fonte do número','Conversas','Apoiadores','Operador','Observação'],...state.metrics.map(m=>[m.date,m.city,m.territory,m.channel,m.approach,m.reach,m.evidence,m.conversations,m.supporters,m.actor,m.note])]),'text/csv;charset=utf-8');if(e.target.id==='export-audit')download('historico-campanha.csv',csv([['Data e hora','Operador','Ação','Detalhe'],...state.audit.map(a=>[a.at,a.actor,a.action,a.detail])]),'text/csv;charset=utf-8');if(e.target.id==='clear-metrics'&&state.metrics.length&&confirm('Excluir todos os registros de alcance deste navegador?')){log('Limpou painel',`${state.metrics.length} registros excluídos`);state.metrics=[];save('Registros removidos.');renderMetrics();renderAudit()}});
document.addEventListener('change',e=>{if(e.target.matches('[data-task]')){state.tasks[e.target.dataset.task]=e.target.checked;log(e.target.checked?'Concluiu tarefa':'Reabriu tarefa',phases[activePhase].title);save();renderNav();renderPhase();updateProgress();renderAudit()}if(e.target.id==='current-user'){state.currentUser=Number(e.target.value);log('Selecionou operador','Início de uso local');save();renderAudit()}});document.addEventListener('input',e=>{if(e.target.matches('[data-answer]'))state.answers[e.target.dataset.answer]=e.target.value});document.querySelector('.menu-button').addEventListener('click',e=>{const open=document.querySelector('#main-nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
document.querySelector('#metric-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),m={city:d.get('city'),channel:d.get('channel'),approach:d.get('approach'),territory:d.get('territory').trim(),date:d.get('date'),reach:Number(d.get('reach')),evidence:d.get('evidence'),conversations:Number(d.get('conversations')),supporters:Number(d.get('supporters')),note:d.get('note').trim(),actor:actor(),createdAt:new Date().toISOString()};state.metrics.push(m);log('Inseriu alcance',`${m.city} · ${m.channel} · ${m.reach.toLocaleString('pt-BR')} pessoas`);save('Alcance salvo.');e.currentTarget.reset();renderMetrics();renderAudit()});
document.querySelector('#settings-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);state.settings={candidateName:d.get('candidateName').trim()||'Kiel Damasceno',slogan:d.get('slogan').trim(),primaryColor:d.get('primaryColor'),accentColor:d.get('accentColor')};log('Alterou identidade','Nome, slogan ou cores');applySettings();save('Identidade aplicada nesta prévia.');renderAudit()});
document.querySelector('#users-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);state.users=state.users.map((_,i)=>String(d.get(`user-${i}`)||defaultUsers[i]).trim());log('Alterou operadores','Atualizou os nomes dos 10 perfis locais');save('Nomes dos operadores salvos.');renderUsers();renderAudit()});
document.querySelector('#import-json').addEventListener('change',async e=>{try{const incoming=JSON.parse(await e.target.files[0].text());if(!incoming||typeof incoming!=='object'||!Array.isArray(incoming.metrics))throw new Error();state={...state,...incoming,settings:{...state.settings,...incoming.settings}};log('Restaurou cópia','Arquivo JSON importado');await save('Cópia restaurada.');applySettings();renderAll()}catch{toast('Arquivo de cópia inválido.')}e.target.value=''});
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1)||'jornada',link=document.querySelector(`[data-view="${id}"]`);if(link)link.click()});load().catch(()=>{toast('Não foi possível abrir o banco local.');renderAll()});
